### ISSUE TITLE
Improvement: Support var args

### ISSUE THREAD

**Issue by ngryman** [jdeal/qim#8]
This library is really neat and navigators is a truly powerful tool, but they impose a kind of "painful" API why may turn some new users away (I know that's silly but...). The main pain-point would be path defined by arrays. It makes perfect sense but it's also sometimes painful to use, error prone, and make the code harder to read.

Would you consider also supporting var args so it becomes:

```js
select('path', 'to', $nav, 'property', state)
```

rel #6

**Comment by jdeal** [comment]
The main problem with that is that it's in conflict with the style of currying used in qim. Var args and currying generally just don't get along. `select` would have to make some kind of arbitrary distinction of where the navigators stop and where the state begins. Even if there was a way to cut that off, the code could be pretty confusing sometimes.

A possible alternative I have discussed is _always_ having `select` and `update` return a function that takes a state object. I do like the explicitness of that, but effectively, it just trades one bit of syntax for another though:

```js
select(['path', 'to', $nav, 'property'], state)
```

vs

```js
select('path', 'to', $nav, 'property')(state)
```

It also adds some unnecessary function garbage overhead in that case, and internally there is likely some parameter-to-array or array-to-parameter marshalling that would have to happen. These are probably pretty small performance differences, but they can affect certain cases where qim would otherwise be relatively transparent performance-wise.

The array-as-path pattern is pretty common, for example in Lodash's `.get` or Immutable.js's `.getIn`. So it didn't seem too unnatural to require it.

**Comment by ngryman** [comment]
Thanks for your comprehensive answer!

I've thought you might have a problem with currying. Correct me if I'm wrong but every function of `qim` are *path-first* / *data-last*. So it's safe to assume the last argument will always be `state`.
Path will always be composed of `string` or `function`, state will always be an `object` (or it's possible you also allow primitive (rtfm)). If so it's kind of safe to curry the function until it receive an `object`?

**Comment by jdeal** [comment]
@ngryman Some of the convenience functions have other arguments. Look at [`set`](https://github.com/jdeal/qim#setquery-value-object) for example.

```js
set('foo', 'bar', {})
```

Is that saying to return a function that sets `foo.bar` to `{}` or is it saying to set `foo` to `bar` in an empty state object `{}`?

Even `update` and `select` are risky though. Some navigators are objects with special keys. It's better IMO to throw and error saying that something is an invalid navigator rather than accidentally consider it to be a state object.

Probably most importantly, arrays are valid navigators used for [nesting queries](https://github.com/jdeal/qim#nested-array), and arrays are perfectly valid state objects. There's no way to distinguish those two cases.

And yes, primitives are also valid state, so this:

```js
update([$apply(n => n + 1)], 0)
```

for example, will give you 1. Not terribly useful, but I don't see much reason to disable that, given all the other reasons to keep it as-is.

**Comment by ngryman** [comment]
@jdeal Good points.

It makes me think about fluent APIs and library like LoDash. When do we detect this is the end of the chain? In LoDash for example you would call `.value()` to actually trigger it.

So why not having a *special* navigator `$end` (or similar), that would tell `qim` this is the end of the path, the next values will be specific to the function.

To take your `set` example:
```js
// return a function that set `foo.bar` to `{}`
set('foo', 'bar', $end, {})

// apply `set` setting `foo` to `bar` taking the state
set('foo', $end, 'bar', {})

// possible shortcut: direct application if the number of arguments is equal to
// the arity of the function.
// apply `set` setting `foo` to `bar` taking the state
set('foo', 'bar', {})
```

What if `qim` proposed those 2 flavors? Or do you think it's easily doable in userland?

**Comment by ngryman** [comment]
TBH after some thoughts, I think my proposition would only bring more complexity to the current API...

**Comment by jdeal** [comment]
Appreciate the brainstorming here! I racked my brain for a  while on the API and went through many different iterations. Happy to see someone else burning some cycles on this. :-)

`set` is actually (conceptually anyway) just sugar over `update`. The idea is to make qim just as terse as lodash/fp's `set` or Ramda's `assocPath` for that simple case.

Note that using the `$end` navigator would make things _less_ terse:

```js
set('foo', $end, 'bar', {})
set(['foo'], 'bar', {})
```

I could potentially be talked into removing `set` though, since I don't actually use it. The same is actually true for `update` as well though:

```js
update('foo', $set('bar'), $end, {})
update(['foo', $set('bar')], {})
```

Note `$end` is already a navigator too, so we'd have to find something else. Assuming the performance cost would be negligible, I'd rather just have `update` always return a function like I mentioned earlier:

```js
update('foo', $set('bar'))({})
```

And the other functions would follow (if I kept them at all):

```js
set('foo', 'bar')({})
```

As I mentioned, I do feel like this is kind of just trading `[]` for `)(` in some cases.

I also considered making the state the first parameter, so:

```js
update({}, ['foo', $set('bar')])
```

If I did that, for `update` at least, the brackets aren't really necessary:

```js
update({}, 'foo', $set('bar'))
```

But of course, that kills off currying, since data needs to be last. So using `update` inside `$apply` for example, gets uglier. I _could_ then create some other navigators like `$update` to cover some common cases, but like you alluded to: I was trying to keep the API/navigator surface area as small as possible. Currying and array-paths seemed to be the best way to do that.

**Comment by ngryman** [comment]
@jdeal Everything you say make sense and I totally agree with it.

I also considered the *data-first* argument but you lose the ability to write *FP* code which would make things uglier indeed.

Then there is the 2 step call (`set('foo', 'bar')({})`). After some thoughts, I kind of like it because it makes things clear:
 1. *path* construction
 2. *data* processing

If we compare the two styles:
 - Old: `set(['foo', 'bar'], state)`
 - New: `set('foo', 'bar')(state)`

I must say that I find the later more readable, self explanatory and less error prone:

 - **More readable** because less different chars to parse with the eye (`[`, `]`, `,` striped) which can make a difference in a big reducer for example where `qim` is used a lot.

 - **Self explanatory** because it feels functional and any modern JavaScript developer will understand this at first glance. It recalls some widely used patterns in the industry like Higher Order Components that typically have a two step call API: *configuration* / *application*.

 - **Less error prone**, (and this is personal) because sometimes I just forget to pass my `state` as last argument. I do this because it's just an argument like the others and the API does not force me to call another function to do so in place. I don't know how to express this in english but basically auto-curry can make API boundaries fuzzy.

At the end it's just a matter of taste, but I think 2 step calls wins here because it's clear and well known, arrays feels like they are not here by choice and clutters things a lot.

On a side note, *APi design* is an interesting topic. I truly think that a comfy API offers true benefits:
 1. less reading fatigue
 2. less error prone
 3. enjoyable -> indirect productivity boost
 4. part of the success of the library

**Comment by jdeal** [comment]
Note that your "old" example isn't quite valid. That needs to be:

```js
set(['foo'], 'bar', state)
```

I think that mistake _may_ be indicative of a slight problem wrt `set` and the 2 step call. Let's look at a slightly more complex/realistic example to illustrate:

```js
// current api
set(['todos', 'todo1', 'text'], 'hello', state)
```

```js
// proposed api
set('todos', 'todo1', 'text', 'hello')(state)
```

Note in the latter, there's nothing visually distinguishing the path from the value. To really be consistent with `update` where the different types of arguments are separated by calls, this would be required:

```js
set('todos', 'todo1', 'text')('hello')(state)
```

Now our visual separation is back, but that's getting a little freaky. Maybe `set` should just be dropped from the api, but it does help illustrate that not everything fits the two-step configuration/application pattern. `set` has two parts for its configuration. Or two parts for its application. Depends on how you look at it.

A similar problem exists with [`$nav`](https://github.com/jdeal/qim#navpath-morepaths) which accepts multiple queries. You can't pass multiple queries to a function if the queries are represented as var args. That means that `$nav` would have to retain the arrays-as-queries signature as a special case. Perhaps this is fine because `$nav` can be said to treat sub-queries differently, and sub-queries are already arrays. But I could see people easily making this mistake:

```js
const $todos = $nav('entities', 'todos');
const newState = update($todos, 'todo1', 'text', $set('hello'))(state);
```

I'd probably end up wanting to split `$nav` into multiple navigators like `$query`, `$many`, and `$dynamic`. Which might arguably be a good thing. `¯\_(ツ)_/¯` But I wouldn't want to take such a change too lightly. Again, at the very least, this again illustrates that the current query-as-array pattern is unambiguous vs the proposed pattern. Also, it would break the heck out of the blog post I wrote. 😅

**Comment by ngryman** [comment]
I totally get your point of view on this, and again it makes perfect sense.

QAA (query-as-array) is explicit, not ambiguous, that's for sure. It just feels *heavy* and I wanted to explore other ways to make things less explicit and more comfy. But you have already walked through the process and explained me why it's very hard to get rid of them. So I have to admit that the current API is probably the best choice given the constraints of the library.

Anyway the user can twist this the way he wants to get rid of QAA if (like me) he really wants to.

Thank you for your time, and good luck for the future! ✌️

**Comment by jdeal** [comment]
Thanks for exploring @ngryman ! If you play around in userland and come up with other ideas (or just want to reaffirm this one later), let me know!
